package anya.pizza.houseki.datagen;

import anya.pizza.houseki.block.ModBlocks;
import anya.pizza.houseki.item.ModArmorMaterials;
import anya.pizza.houseki.item.ModItems;
import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.client.datagen.v1.provider.FabricModelProvider;
import net.minecraft.client.data.*;

public class ModModelProvider extends FabricModelProvider {
    public ModModelProvider(FabricDataOutput output) {
        super(output);
    }

    @Override
    public void generateBlockStateModels(BlockStateModelGenerator blockStateModelGenerator) {
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.PINKU_ORE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BLOCK_OF_PINKU);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.WOLFRAMITE_ORE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.NETHERRACK_WOLFRAMITE_ORE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.RAINBOW_PYRITE_ORE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BAUXITE_RAINBOW_PYRITE_ORE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BLOCK_OF_RAINBOW_PYRITE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.SCHEELITE_ORE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BLOCK_OF_TUNGSTEN_B);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BAUXITE);
        blockStateModelGenerator.registerGlassAndPane(ModBlocks.ALUMINUM_GLASS, ModBlocks.ALUMINUM_GLASS_PANE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BLOCK_OF_ALUMINUM);
        blockStateModelGenerator.registerDoor(ModBlocks.ALUMINUM_DOOR);
        blockStateModelGenerator.registerTrapdoor(ModBlocks.ALUMINUM_TRAPDOOR);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BLOCK_OF_SAPPHIRE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.SAPPHIRE_ORE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.DEEPSLATE_SAPPHIRE_ORE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.NEPHRITE_ORE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.JADEITE_ORE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BLOCK_OF_JADEITE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BLOCK_OF_PLATINUM);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.DEEPSLATE_PLATINUM_ORE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.PLATINUM_ORE);
        BlockStateModelGenerator.BlockTexturePool limestoneBrickPool = blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.LIMESTONE_BRICKS);
        BlockStateModelGenerator.BlockTexturePool limestonePool = blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.LIMESTONE);
        BlockStateModelGenerator.BlockTexturePool polishedLimestonePool = blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.POLISHED_LIMESTONE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.CHISELED_LIMESTONE);
        BlockStateModelGenerator.BlockTexturePool slateTilesPool = blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.SLATE_TILES);
        BlockStateModelGenerator.BlockTexturePool slatePool = blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.SLATE);
        BlockStateModelGenerator.BlockTexturePool polishedSlatePool = blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.POLISHED_SLATE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.CHISELED_SLATE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BLACKSTONE_SULFUR_ORE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.SULFUR_ORE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BLOCK_OF_SULFUR);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BLOCK_OF_STEEL);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BLOCK_OF_CAST_STEEL_B);

        blockStateModelGenerator.registerCooker(ModBlocks.CRUSHER, TexturedModel.ORIENTABLE);

        limestonePool.stairs(ModBlocks.LIMESTONE_STAIRS);
        limestoneBrickPool.stairs(ModBlocks.LIMESTONE_BRICK_STAIRS);
        polishedLimestonePool.stairs(ModBlocks.POLISHED_LIMESTONE_STAIRS);
        limestonePool.slab(ModBlocks.LIMESTONE_SLAB);
        limestoneBrickPool.slab(ModBlocks.LIMESTONE_BRICK_SLAB);
        polishedLimestonePool.slab(ModBlocks.POLISHED_LIMESTONE_SLAB);
        limestonePool.wall(ModBlocks.LIMESTONE_WALL);
        limestoneBrickPool.wall(ModBlocks.LIMESTONE_BRICK_WALL);
        polishedLimestonePool.wall(ModBlocks.POLISHED_LIMESTONE_WALL);
        slatePool.stairs(ModBlocks.SLATE_STAIRS);
        slateTilesPool.stairs(ModBlocks.SLATE_TILE_STAIRS);
        polishedSlatePool.stairs(ModBlocks.POLISHED_SLATE_STAIRS);
        slatePool.slab(ModBlocks.SLATE_SLAB);
        slateTilesPool.slab(ModBlocks.SLATE_TILE_SLAB);
        polishedSlatePool.slab(ModBlocks.POLISHED_SLATE_SLAB);
        slatePool.wall(ModBlocks.SLATE_WALL);
        slateTilesPool.wall(ModBlocks.SLATE_TILE_WALL);
        polishedSlatePool.wall(ModBlocks.POLISHED_SLATE_WALL);
    }

    @Override
    public void generateItemModels(ItemModelGenerator itemModelGenerator) {
        itemModelGenerator.register(ModItems.RAINBOW_PYRITE, Models.GENERATED);
        itemModelGenerator.register(ModItems.PINKU, Models.GENERATED);
        itemModelGenerator.register(ModItems.PINKU_SHARD, Models.GENERATED);
        itemModelGenerator.register(ModItems.WOLFRAMITE, Models.GENERATED);
        itemModelGenerator.register(ModItems.SCHEELITE, Models.GENERATED);
        itemModelGenerator.register(ModItems.TUNGSTEN, Models.GENERATED);
        itemModelGenerator.register(ModItems.CRUSHED_BAUXITE, Models.GENERATED);
        itemModelGenerator.register(ModItems.ALUMINUM, Models.GENERATED);
        itemModelGenerator.register(ModItems.SAPPHIRE, Models.GENERATED);
        itemModelGenerator.register(ModItems.NEPHRITE, Models.GENERATED);
        itemModelGenerator.register(ModItems.JADEITE, Models.GENERATED);
        itemModelGenerator.register(ModItems.PLATINUM, Models.GENERATED);
        itemModelGenerator.register(ModItems.PLATINUM_NUGGET, Models.GENERATED);
        itemModelGenerator.register(ModItems.SULFUR, Models.GENERATED);
        itemModelGenerator.register(ModItems.CRUDE_IRON, Models.GENERATED);
        itemModelGenerator.register(ModItems.STEEL, Models.GENERATED);
        itemModelGenerator.register(ModItems.CAST_STEEL, Models.GENERATED);
        itemModelGenerator.register(ModItems.TUNGSTEN_DRILL_BIT, Models.GENERATED);
        itemModelGenerator.register(ModItems.SIMPLE_DRILL_HEAD, Models.GENERATED);
        itemModelGenerator.register(ModItems.ENHANCED_DRILL_HEAD, Models.GENERATED);
        itemModelGenerator.register(ModItems.ADVANCED_DRILL_HEAD, Models.GENERATED);
        itemModelGenerator.register(ModItems.PREMIUM_DRILL_HEAD, Models.GENERATED);
        itemModelGenerator.register(ModItems.DIAMOND_DRILL_BIT, Models.GENERATED);

        itemModelGenerator.register(ModItems.PINKU_UPGRADE_SMITHING_TEMPLATE, Models.GENERATED);
        itemModelGenerator.register(ModItems.DRILL_UPGRADE_SMITHING_TEMPLATE, Models.GENERATED);

        itemModelGenerator.register(ModItems.PINKU_PICKAXE, Models.HANDHELD);
        itemModelGenerator.register(ModItems.PINKU_AXE, Models.HANDHELD);
        itemModelGenerator.register(ModItems.PINKU_SHOVEL, Models.HANDHELD);
        itemModelGenerator.register(ModItems.PINKU_SWORD, Models.HANDHELD);
        itemModelGenerator.register(ModItems.PINKU_HOE, Models.HANDHELD);
        itemModelGenerator.register(ModItems.PINKU_SPEAR, Models.HANDHELD);
        itemModelGenerator.register(ModItems.RAINBOW_PYRITE_PICKAXE, Models.HANDHELD);
        itemModelGenerator.register(ModItems.RAINBOW_PYRITE_AXE, Models.HANDHELD);
        itemModelGenerator.register(ModItems.RAINBOW_PYRITE_SHOVEL, Models.HANDHELD);
        itemModelGenerator.register(ModItems.RAINBOW_PYRITE_SWORD, Models.HANDHELD);
        itemModelGenerator.register(ModItems.RAINBOW_PYRITE_HOE, Models.HANDHELD);
        itemModelGenerator.register(ModItems.RAINBOW_PYRITE_SPEAR, Models.HANDHELD);
        itemModelGenerator.register(ModItems.TUNGSTEN_PICKAXE, Models.HANDHELD);
        itemModelGenerator.register(ModItems.TUNGSTEN_AXE, Models.HANDHELD);
        itemModelGenerator.register(ModItems.TUNGSTEN_SHOVEL, Models.HANDHELD);
        itemModelGenerator.register(ModItems.TUNGSTEN_SWORD, Models.HANDHELD);
        itemModelGenerator.register(ModItems.TUNGSTEN_HOE, Models.HANDHELD);
        itemModelGenerator.register(ModItems.TUNGSTEN_SPEAR, Models.HANDHELD);
        itemModelGenerator.register(ModItems.SIMPLE_TUNGSTEN_DRILL, Models.HANDHELD);
        itemModelGenerator.register(ModItems.ENHANCED_TUNGSTEN_DRILL, Models.HANDHELD);
        itemModelGenerator.register(ModItems.ADVANCED_TUNGSTEN_DRILL, Models.HANDHELD);
        itemModelGenerator.register(ModItems.PREMIUM_TUNGSTEN_DRILL, Models.HANDHELD);
        itemModelGenerator.register(ModItems.ALUMINUM_PICKAXE, Models.HANDHELD);
        itemModelGenerator.register(ModItems.ALUMINUM_AXE, Models.HANDHELD);
        itemModelGenerator.register(ModItems.ALUMINUM_SHOVEL, Models.HANDHELD);
        itemModelGenerator.register(ModItems.ALUMINUM_SWORD, Models.HANDHELD);
        itemModelGenerator.register(ModItems.ALUMINUM_HOE, Models.HANDHELD);
        itemModelGenerator.register(ModItems.ALUMINUM_SPEAR, Models.HANDHELD);
        itemModelGenerator.register(ModItems.SAPPHIRE_PICKAXE, Models.HANDHELD);
        itemModelGenerator.register(ModItems.SAPPHIRE_AXE, Models.HANDHELD);
        itemModelGenerator.register(ModItems.SAPPHIRE_SHOVEL, Models.HANDHELD);
        itemModelGenerator.register(ModItems.SAPPHIRE_SWORD, Models.HANDHELD);
        itemModelGenerator.register(ModItems.SAPPHIRE_HOE, Models.HANDHELD);
        itemModelGenerator.register(ModItems.SAPPHIRE_SPEAR, Models.HANDHELD);
        itemModelGenerator.register(ModItems.NEPHRITE_PICKAXE, Models.HANDHELD);
        itemModelGenerator.register(ModItems.NEPHRITE_AXE, Models.HANDHELD);
        itemModelGenerator.register(ModItems.NEPHRITE_SHOVEL, Models.HANDHELD);
        itemModelGenerator.register(ModItems.NEPHRITE_SWORD, Models.HANDHELD);
        itemModelGenerator.register(ModItems.NEPHRITE_HOE, Models.HANDHELD);
        itemModelGenerator.register(ModItems.NEPHRITE_SPEAR, Models.HANDHELD);
        itemModelGenerator.register(ModItems.JADEITE_PICKAXE, Models.HANDHELD);
        itemModelGenerator.register(ModItems.JADEITE_AXE, Models.HANDHELD);
        itemModelGenerator.register(ModItems.JADEITE_SHOVEL, Models.HANDHELD);
        itemModelGenerator.register(ModItems.JADEITE_SWORD, Models.HANDHELD);
        itemModelGenerator.register(ModItems.JADEITE_HOE, Models.HANDHELD);
        itemModelGenerator.register(ModItems.JADEITE_SPEAR, Models.HANDHELD);
        itemModelGenerator.register(ModItems.PLATINUM_PICKAXE, Models.HANDHELD);
        itemModelGenerator.register(ModItems.PLATINUM_AXE, Models.HANDHELD);
        itemModelGenerator.register(ModItems.PLATINUM_SHOVEL, Models.HANDHELD);
        itemModelGenerator.register(ModItems.PLATINUM_SWORD, Models.HANDHELD);
        itemModelGenerator.register(ModItems.PLATINUM_HOE, Models.HANDHELD);
        itemModelGenerator.register(ModItems.PLATINUM_SPEAR, Models.HANDHELD);
        itemModelGenerator.register(ModItems.CAST_STEEL_PICKAXE, Models.HANDHELD);
        itemModelGenerator.register(ModItems.CAST_STEEL_AXE, Models.HANDHELD);
        itemModelGenerator.register(ModItems.CAST_STEEL_SHOVEL, Models.HANDHELD);
        itemModelGenerator.register(ModItems.CAST_STEEL_SWORD, Models.HANDHELD);
        itemModelGenerator.register(ModItems.CAST_STEEL_HOE, Models.HANDHELD);
        itemModelGenerator.register(ModItems.CAST_STEEL_SPEAR, Models.HANDHELD);
        itemModelGenerator.register(ModItems.SIMPLE_DIAMOND_DRILL, Models.HANDHELD);
        itemModelGenerator.register(ModItems.ENHANCED_DIAMOND_DRILL, Models.HANDHELD);
        itemModelGenerator.register(ModItems.ADVANCED_DIAMOND_DRILL, Models.HANDHELD);
        itemModelGenerator.register(ModItems.PREMIUM_DIAMOND_DRILL, Models.HANDHELD);

        itemModelGenerator.registerArmor(ModItems.PINKU_HELMET, ModArmorMaterials.PINKU_KEY, ItemModelGenerator.HELMET_TRIM_ID_PREFIX, false);
        itemModelGenerator.registerArmor(ModItems.PINKU_CHESTPLATE, ModArmorMaterials.PINKU_KEY, ItemModelGenerator.CHESTPLATE_TRIM_ID_PREFIX, false);
        itemModelGenerator.registerArmor(ModItems.PINKU_LEGGINGS, ModArmorMaterials.PINKU_KEY, ItemModelGenerator.LEGGINGS_TRIM_ID_PREFIX, false);
        itemModelGenerator.registerArmor(ModItems.PINKU_BOOTS, ModArmorMaterials.PINKU_KEY, ItemModelGenerator.BOOTS_TRIM_ID_PREFIX, false);
        itemModelGenerator.registerArmor(ModItems.RAINBOW_PYRITE_HELMET, ModArmorMaterials.RAINBOW_PYRITE_KEY, ItemModelGenerator.HELMET_TRIM_ID_PREFIX, false);
        itemModelGenerator.registerArmor(ModItems.RAINBOW_PYRITE_CHESTPLATE, ModArmorMaterials.RAINBOW_PYRITE_KEY, ItemModelGenerator.CHESTPLATE_TRIM_ID_PREFIX, false);
        itemModelGenerator.registerArmor(ModItems.RAINBOW_PYRITE_LEGGINGS,  ModArmorMaterials.RAINBOW_PYRITE_KEY, ItemModelGenerator.LEGGINGS_TRIM_ID_PREFIX, false);
        itemModelGenerator.registerArmor(ModItems.RAINBOW_PYRITE_BOOTS, ModArmorMaterials.RAINBOW_PYRITE_KEY, ItemModelGenerator.BOOTS_TRIM_ID_PREFIX, false);
        itemModelGenerator.registerArmor(ModItems.TUNGSTEN_HELMET, ModArmorMaterials.TUNGSTEN_KEY, ItemModelGenerator.HELMET_TRIM_ID_PREFIX, false);
        itemModelGenerator.registerArmor(ModItems.TUNGSTEN_CHESTPLATE, ModArmorMaterials.TUNGSTEN_KEY, ItemModelGenerator.CHESTPLATE_TRIM_ID_PREFIX, false);
        itemModelGenerator.registerArmor(ModItems.TUNGSTEN_LEGGINGS,  ModArmorMaterials.TUNGSTEN_KEY, ItemModelGenerator.LEGGINGS_TRIM_ID_PREFIX, false);
        itemModelGenerator.registerArmor(ModItems.TUNGSTEN_BOOTS, ModArmorMaterials.TUNGSTEN_KEY, ItemModelGenerator.BOOTS_TRIM_ID_PREFIX, false);
        itemModelGenerator.registerArmor(ModItems.ALUMINUM_HELMET, ModArmorMaterials.ALUMINUM_KEY, ItemModelGenerator.HELMET_TRIM_ID_PREFIX, false);
        itemModelGenerator.registerArmor(ModItems.ALUMINUM_CHESTPLATE, ModArmorMaterials.ALUMINUM_KEY, ItemModelGenerator.CHESTPLATE_TRIM_ID_PREFIX, false);
        itemModelGenerator.registerArmor(ModItems.ALUMINUM_LEGGINGS,  ModArmorMaterials.ALUMINUM_KEY, ItemModelGenerator.LEGGINGS_TRIM_ID_PREFIX, false);
        itemModelGenerator.registerArmor(ModItems.ALUMINUM_BOOTS, ModArmorMaterials.ALUMINUM_KEY, ItemModelGenerator.BOOTS_TRIM_ID_PREFIX, false);
        itemModelGenerator.registerArmor(ModItems.SAPPHIRE_HELMET, ModArmorMaterials.SAPPHIRE_KEY, ItemModelGenerator.HELMET_TRIM_ID_PREFIX, false);
        itemModelGenerator.registerArmor(ModItems.SAPPHIRE_CHESTPLATE, ModArmorMaterials.SAPPHIRE_KEY, ItemModelGenerator.CHESTPLATE_TRIM_ID_PREFIX, false);
        itemModelGenerator.registerArmor(ModItems.SAPPHIRE_LEGGINGS,  ModArmorMaterials.SAPPHIRE_KEY, ItemModelGenerator.LEGGINGS_TRIM_ID_PREFIX, false);
        itemModelGenerator.registerArmor(ModItems.SAPPHIRE_BOOTS, ModArmorMaterials.SAPPHIRE_KEY, ItemModelGenerator.BOOTS_TRIM_ID_PREFIX, false);
        itemModelGenerator.registerArmor(ModItems.NEPHRITE_HELMET, ModArmorMaterials.NEPHRITE_KEY, ItemModelGenerator.HELMET_TRIM_ID_PREFIX, false);
        itemModelGenerator.registerArmor(ModItems.NEPHRITE_CHESTPLATE, ModArmorMaterials.NEPHRITE_KEY, ItemModelGenerator.CHESTPLATE_TRIM_ID_PREFIX, false);
        itemModelGenerator.registerArmor(ModItems.NEPHRITE_LEGGINGS,  ModArmorMaterials.NEPHRITE_KEY, ItemModelGenerator.LEGGINGS_TRIM_ID_PREFIX, false);
        itemModelGenerator.registerArmor(ModItems.NEPHRITE_BOOTS, ModArmorMaterials.NEPHRITE_KEY, ItemModelGenerator.BOOTS_TRIM_ID_PREFIX, false);
        itemModelGenerator.registerArmor(ModItems.JADEITE_HELMET, ModArmorMaterials.JADEITE_KEY, ItemModelGenerator.HELMET_TRIM_ID_PREFIX, false);
        itemModelGenerator.registerArmor(ModItems.JADEITE_CHESTPLATE, ModArmorMaterials.JADEITE_KEY, ItemModelGenerator.CHESTPLATE_TRIM_ID_PREFIX, false);
        itemModelGenerator.registerArmor(ModItems.JADEITE_LEGGINGS,  ModArmorMaterials.JADEITE_KEY, ItemModelGenerator.LEGGINGS_TRIM_ID_PREFIX, false);
        itemModelGenerator.registerArmor(ModItems.JADEITE_BOOTS, ModArmorMaterials.JADEITE_KEY, ItemModelGenerator.BOOTS_TRIM_ID_PREFIX, false);
        itemModelGenerator.registerArmor(ModItems.PLATINUM_HELMET, ModArmorMaterials.PLATINUM_KEY, ItemModelGenerator.HELMET_TRIM_ID_PREFIX, false);
        itemModelGenerator.registerArmor(ModItems.PLATINUM_CHESTPLATE, ModArmorMaterials.PLATINUM_KEY, ItemModelGenerator.CHESTPLATE_TRIM_ID_PREFIX, false);
        itemModelGenerator.registerArmor(ModItems.PLATINUM_LEGGINGS,  ModArmorMaterials.PLATINUM_KEY, ItemModelGenerator.LEGGINGS_TRIM_ID_PREFIX, false);
        itemModelGenerator.registerArmor(ModItems.PLATINUM_BOOTS, ModArmorMaterials.PLATINUM_KEY, ItemModelGenerator.BOOTS_TRIM_ID_PREFIX, false);
        itemModelGenerator.registerArmor(ModItems.CAST_STEEL_HELMET, ModArmorMaterials.CAST_STEEL_KEY, ItemModelGenerator.HELMET_TRIM_ID_PREFIX, false);
        itemModelGenerator.registerArmor(ModItems.CAST_STEEL_CHESTPLATE, ModArmorMaterials.CAST_STEEL_KEY, ItemModelGenerator.CHESTPLATE_TRIM_ID_PREFIX, false);
        itemModelGenerator.registerArmor(ModItems.CAST_STEEL_LEGGINGS,  ModArmorMaterials.CAST_STEEL_KEY, ItemModelGenerator.LEGGINGS_TRIM_ID_PREFIX, false);
        itemModelGenerator.registerArmor(ModItems.CAST_STEEL_BOOTS, ModArmorMaterials.CAST_STEEL_KEY, ItemModelGenerator.BOOTS_TRIM_ID_PREFIX, false);

        itemModelGenerator.register(ModItems.PINKU_HORSE_ARMOR, Models.GENERATED);
        itemModelGenerator.register(ModItems.RAINBOW_PYRITE_HORSE_ARMOR, Models.GENERATED);
        itemModelGenerator.register(ModItems.TUNGSTEN_HORSE_ARMOR, Models.GENERATED);
        itemModelGenerator.register(ModItems.ALUMINUM_HORSE_ARMOR, Models.GENERATED);
        itemModelGenerator.register(ModItems.SAPPHIRE_HORSE_ARMOR, Models.GENERATED);
        itemModelGenerator.register(ModItems.PLATINUM_HORSE_ARMOR, Models.GENERATED);
        itemModelGenerator.register(ModItems.CAST_STEEL_HORSE_ARMOR, Models.GENERATED);
        itemModelGenerator.register(ModItems.NEPHRITE_HORSE_ARMOR, Models.GENERATED);
        itemModelGenerator.register(ModItems.JADEITE_HORSE_ARMOR, Models.GENERATED);

        itemModelGenerator.register(ModItems.PINKU_NAUTILUS_ARMOR, Models.GENERATED);
        itemModelGenerator.register(ModItems.RAINBOW_PYRITE_NAUTILUS_ARMOR, Models.GENERATED);
        itemModelGenerator.register(ModItems.TUNGSTEN_NAUTILUS_ARMOR, Models.GENERATED);
        itemModelGenerator.register(ModItems.ALUMINUM_NAUTILUS_ARMOR, Models.GENERATED);
        itemModelGenerator.register(ModItems.SAPPHIRE_NAUTILUS_ARMOR, Models.GENERATED);
        itemModelGenerator.register(ModItems.PLATINUM_NAUTILUS_ARMOR, Models.GENERATED);
        itemModelGenerator.register(ModItems.CAST_STEEL_NAUTILUS_ARMOR, Models.GENERATED);
        itemModelGenerator.register(ModItems.NEPHRITE_NAUTILUS_ARMOR, Models.GENERATED);
        itemModelGenerator.register(ModItems.JADEITE_NAUTILUS_ARMOR, Models.GENERATED);
    }
}